# Generated by Django 5.1.3 on 2024-11-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the course",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/pictures",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the course",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the lesson",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/pictures",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describe the lesson",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "video",
                    models.TextField(
                        help_text="Add the link to the video", verbose_name="Video URL"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
